### ISSUE TITLE
Bug: v0.7.0 - Error while requiring module `vitest-environment-nuxt/module`: Error: Cannot find module 'vitest-environment-nuxt/module'

### ISSUE THREAD

**Issue by silverbackdan** [danielroe/nuxt-vitest#171]
It seems after upgrading to 0.7.0 with vitest 0.31 I receive the error:
```
Error while requiring module `vitest-environment-nuxt/module`: Error: Cannot find module 'vitest-environment-nuxt/module'
```

Which looks like it is trying to be installed by the module required for this package.

Strange though as I see `vitest-environment-nuxt` as a dependency in the package.json

It could be @nuxt/test-utils > vitest conflicting versions. I'll do some digging.

**Comment by silverbackdan** [comment]
Also see another user with this issue in comments of the closed issue here: https://github.com/danielroe/nuxt-vitest/issues/68

**Comment by huntz20** [comment]
Same thing happen to me after installing nuxt-vitest 

when runing test i getting this error 
```
Error: Failed to load url /packages/nuxt/dist/app/index/entry (resolved id: /packages/nuxt/dist/app/index/entry) in /Users/huntz/WebstormProjects/petal/node_modules/vitest-environment-nuxt/dist/index.mjs. Does the file exist?
    at loadAndTransform (file:///Users/huntz/WebstormProjects/petal/node_modules/vite/dist/node/chunks/dep-4d3eff22.js:53376:21)
```

**Comment by ThomasWT** [comment]
The only way I could make this work was
`npm remove vitest @nuxt/test-utils`

then installing these 2 with the specific versions.
```
"nuxt-vitest": "^0.6.8",
"vitest-environment-nuxt": "^0.7.0"
```

There seems to be a dependency conflict between vitest@0.31.1, @nuxt/test-utils@3.5.0 and nuxt-vitest@0.7.0

**Comment by silverbackdan** [comment]
I'm not definite but I'm pretty sure https://github.com/danielroe/nuxt-vitest/pull/185 should resolve this if you wanted to check

**Comment by danielroe** [comment]
This should be resolved in the latest version of Nuxt (v3.5.2) via https://github.com/nuxt/nuxt/pull/21082.
