### ISSUE TITLE
Error after updating happy dom dependency

### ISSUE THREAD

**Issue by morgan-massamba** [danielroe/nuxt-vitest#276]
After updating happy-dom to the latest version **10.5.2** ,
I have this error when I run my app : 
`Error while requiring module vitest-environment-nuxt/module: Error: Cannot find module '/Users/<user>/<folderpath>/vitest-environment-nuxt/module'`

Does anyone have a solution ?

**Comment by danielroe** [comment]
Does it make a difference if you add `vitest-environment-nuxt` as an explicit dependency?

**Comment by vsanrocha** [comment]
@morgan-massamba, add the `happy-dom` manually using `yarn add -D happy-dom` or `npm install --save-dev happy-dom`.

@danielroe, the `happy-dom` isn't installed by default with the package.

**Comment by danielroe** [comment]
No, it's deliberately no longer installed by default. You can choose to install either happy-dom or jsdom.

**Comment by morgan-massamba** [comment]
After updating nuxt-vitest to 0.10.2 , I no longer have this issue.
I think this solved it https://github.com/danielroe/nuxt-vitest/commit/94e0768c27b076ed5faed7faa79327428991918e

Thanks for your help 👍
